= Enonic Applications
:toc: right
:imagesdir: images

Build and deploy schemas, code, and functionality via Enonic applications.

== Introduction

An *Enonic application* is a named package of functionality that XP installs, starts and configures as one unit. The application name is unique within an installation, and everything the application ships is identified by it: schemas, endpoints, tools, extensions, jobs and configuration. Many applications run side by side in one XP instance, and most of XP's own components are applications.

An application may contain nothing but CMS schemas, or code that serves a site or an API, or Java components, or all of these. Once started, it has access to all platform services, including the <<storage#, NoSQL storage>> and <<security#, identity and access management>>.

== Enonic Market

https://market.enonic.com[Enonic market] is the go-to place for official apps from Enonic, as well as 3rd party applications. The marketplace also offers starter kits and software libraries that help you create new apps better and faster.

== Installation

There are four ways to get your applications running on Enonic XP:

Via Admin Interface:: Applications can be manually installed through the <<admin/applications#, Applications admin tool>>, included with Enonic XP. Once installed, the applications will be available for all nodes in an XP cluster.

Via Management API:: Applications can be installed through the Management API. The applications will be available for all nodes in an XP cluster. This approach is commonly used in a CI/CD setup.

Via File system:: File system deployment is most commonly used during development, but it can also be applied for specialized deployment scenarios. Applications deployed on file will only be available on the local node, and overrides applications installed via other alternatives.

Microservice bundle:: Consider a microservice style highly controlled setup where you bundle your app(s) together with the XP runtime and launch it as a separate instance.

== Life cycle

In addition to installing and uninstalling, Enonic applications may be started and stopped. This is referred to as the life cycle of the application. During the stop and start phases, applications themselves may execute custom code.

Starting:: Once installed, applications are automatically started on all nodes. During startup, if it exists, the application's `main.js` script will be executed.

Stopping:: Before uninstalling, applications are automatically stopped on all nodes. During stopping, if it exists, the disposer of the application's `main.js` script will be executed.

== Configuration

Applications can be configured by adding a <<config/system#, custom configuration file>> `<app-name>.cfg` (i.e. `my.custom.app.cfg`) to your Enonic instance.

== Building applications

For what an application can contain and how to build one, see https://developer.enonic.com/docs/code/stable/apps[Applications] in the Enonic Development Kit.
