= Enonic XP8 Platform Documentation
include::.variables.adoc[]
:toc: right
:imagesdir: images

This documentation covers the core platform features and architecture.

TIP: *Looking for the https://developer.enonic.com/docs/cms[CMS docs]?* 


== Built like an operating system

XP is a self-contained platform with an ecosystem of applications that run on top.

image::platform.svg[Iceberg illustration - platform under water applications above the surface,1440]
Based on original illustration from https://www.vecteezy.com/free-vector/unity[Unity Vectors by Vecteezy]

== Apps

Standalone software packages that can be installed and started on Enonic XP with access to all platform services and APIs. Use them to add specific features and functionality to your instance, ranging from APIs to administrative interfaces.

TIP: *Building your own apps?*  Visit https://developer.enonic.com/docs/code[Enonic Development Kit] documentation. 

TIP: *Visit https://market.enonic.com[Enonic Market]* for official apps from Enonic, and 3rd party developers.


== Platform

The platform provides essential services and APIs that applications leverage to build their functionality.

* <<endpoints#,Endpoints>> - HTTP entry points for 3rd party client interactions.
* <<apps#,App runtime>> - Able to power and run multiple applications simultaneously.
* <<security#,Identity and Access Management (IAM)>> - A comprehensive security model for authentication and authorization across the platform.
* Clustering - for distributed memory caching, events and job execution.
* <<storage#,NoSQL storage>> - A built-in NoSQL storage engine for storing content, application- and system data.


== Release notes

Curious about whats new, or how to upgrade from a previous version of XP? Check out the <<release#,release notes>>.

NOTE: If you are looking to upgrade from a previous version of XP, check out the <<upgrade#,Upgrade documentation>>
